# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        uses: ramsey/composer-install@83af392bf5f031813d25e6fe4cd626cdba9a2df6 # 2.2.0

      - name: Run tests
        run: composer test
